import sys

from coip import multicast
from db import db

from ui import TextChangerGUI


def print_usage(help_type):
    print(f'usage: main.{"exe" if getattr(sys, "frozen", False) else "py"} ', end='')
    if help_type == "both":
        print('[', end='')
    if help_type in ("name", "both"):
        print('[[--Script "script name"] [--Nolog]]', end='')
    if help_type == "both":
        print(' | ', end='')
    if help_type in ("script", "both"):
        print('[--Message "message" --Timeout 10 --Addresses 1.1.1.1 [1.1.1.2 ...] [--Nolog]]', end='')
    if help_type == "both":
        print(']', end='')
    print()


if __name__ == "__main__":
    has_help = any(arg in sys.argv for arg in ("-h", "--Help"))
    has_script_name = any(arg in sys.argv for arg in ("-s", "--Script"))
    has_static_script = any(arg in sys.argv for arg in ("-m", "--Message", "-t", "--Timeout", "-a", "--Addresses"))

    if len(sys.argv) == 1:
        TextChangerGUI.launch_gui()
    elif has_script_name and has_static_script:
        print_usage("both")
    elif has_help and has_script_name:
        print("Run a single script generated by the GlobalTime Clock Text Changer GUI application.")
        print_usage("name")
    elif has_help and has_static_script:
        print("Manually multicast to GlobalTime clocks.")
        print_usage("script")
    elif has_help:
        print("Display the GlobalTime Clock Text Changer GUI application.")
        print_usage("")
    elif has_script_name:
        if (not (sys.argv[1] in ("-s", "--Script"))) or (len(sys.argv) == 4 and sys.argv[3] not in ("-n", "--Nolog")):
            print("Invalid arguments.")
            print_usage("name")
        else:
            db_instance = db.DBConn()
            script = db_instance.select_script(sys.argv[2])
            if not script:
                print("That script doesn't exist.")
            else:
                print(multicast.multicast(script[3], script[1], script[2], len(sys.argv) == 3))
    elif has_static_script:
        if len(sys.argv) < 7 or (sys.argv[1] not in ("-m", "--Message")) or (
                sys.argv[3] not in ("-t", "--Timeout")) or (sys.argv[5] not in ("-a", "--Addresses")):
            print_usage("script")
        else:
            print(multicast.multicast(sys.argv[6:], sys.argv[2], sys.argv[4], sys.argv[-1] not in ("-n", "--Nolog")))
    else:
        print("This is the GlobalTime Clock Text Changer.")
        print_usage("both")
